version: '3'
services:
  server1:
    build: './server1'
    ports:
      - "3001:3001"

  server2:
    build: './server2'
    ports:
      - "3002:3002"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server1
      - server2